// <auto-generated />
namespace TempLog.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TdSensorId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TdSensorId));
        
        string IMigrationMetadata.Id
        {
            get { return "201301202256217_TdSensorId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
